import numpy as np
WIN_ADJUST = 50
WINDOW_SIZE = (600, 600)
GRAVITY_1d = -9.8
TIME_INTERVALS = 10
TARGET_POSITION = (0, 500)
START_POSITION = (0, 10)
GROUND_LEVEL = 0
MAX_ROCKET_HEIGHT = 600

MAX_TIME_INTERVALS = 60
MAX_GENERATION = 50
MAX_HORIZONTAL_DEVIATION = 100
MAX_ROCKET_HEIGHT = 600

TIME_INTERVALS_PER_SEC = 10
REFRESH_RATE = 1 / TIME_INTERVALS_PER_SEC
ROCKET_SIZE = 10
ROCKET_MAIN_ENGINE_FORCE = 30
ROCKET_ROTATIONAL_ENGINE_FORCE = 10

GRAVITY = np.array([0.0, -9.8])
